# Generated by Django 2.0.6 on 2018-06-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Convert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileToCovert', models.FileField(upload_to='toCovert/%Y/%m/%d/')),
                ('convertedFile', models.FileField(upload_to='converted/%Y/%m/%d/')),
            ],
        ),
    ]
